#!/bin/sh
#format: alias prefix rprefix hostname port user
#format: pk_alias pubkey
#cs-sabre configuration database
csdb=$(cat $1)
#alias
entryname=$2
#entry
entry=$(echo "$csdb" | grep '^'$entryname' ')
prefix=$(echo $entry | cut -d' ' -f2)
rprefix=$(echo $entry | cut -d' ' -f3)
hostname=$(echo $entry | cut -d' ' -f4)
port=$(echo $entry | cut -d' ' -f5)
user=$(echo $entry | cut -d' ' -f6)
akey=$(cat $3 | sed 's,^,pk_'$entryname' ,')
echo entry=$(echo "$csdb" | grep '^'$entryname' ')
echo prefix=$(echo $entry | cut -d' ' -f2)
echo rprefix=$(echo $entry | cut -d' ' -f3)
echo hostname=$(echo $entry | cut -d' ' -f4)
echo port=$(echo $entry | cut -d' ' -f5)
echo user=$(echo $entry | cut -d' ' -f6)
echo akey=$(cat $3 | sed 's,^,pk_'$entryname' ,')
line=$(echo "$csdb" | grep -n '^'$entryname' ' | cut -d: -f1)
sed -i $line'a'"$akey" $1
