#!/bin/sh
#common header for cs-sabre scripts
#format: alias prefix rprefix hostname port user
#format: pk_alias pubkey
#cs-sabre configuration database
csdb=$(cat $1)
#alias
entryname=$2
#entry
entry=$(echo "$csdb" | grep '^'$entryname' ')
prefix=$(echo $entry | cut -d' ' -f2)
rprefix=$(echo $entry | cut -d' ' -f3)
hostname=$(echo $entry | cut -d' ' -f4)
port=$(echo $entry | cut -d' ' -f5)
user=$(echo $entry | cut -d' ' -f6)
pkey=$(echo "$csdb" | grep '^pk_'$entryname' ' | cut -d' ' -f2-)
echo entry=$(echo "$csdb" | grep '^'$entryname' ')
echo prefix=$(echo $entry | cut -d' ' -f2)
echo rprefix=$(echo $entry | cut -d' ' -f3)
echo hostname=$(echo $entry | cut -d' ' -f4)
echo port=$(echo $entry | cut -d' ' -f5)
echo user=$(echo $entry | cut -d' ' -f6)
echo pkey=$(echo "$csdb" | grep '^pk_'$entryname' ' | cut -d' ' -f2-)
chmod 0600 $prefix/sidearmconnect/sacsshhkey/key
chmod 0600 $prefix/sidearmconnect/sacsshpkey/key
/usr/sbin/sshd -h $prefix/sidearmconnect/sacsshhkey/key -p "$1"
