#!/bin/sh
#This header file defines the variables interpreted by d2efbuild.
#Each variable can be called in a header definition file, to make it easier to define a variable.
sq=\'
dq=\"
pchar=\|
redir=\>
bksh=\\
apnd='>>'
pos='cut -d'${sq}' '${sq}' -f'
linum='grep -n '$sq'.\?'$sq
ln='head -n1'
tr='tr -d \n'
q86='qemu-system-x86 -machine q35 -cpu max -accel kvm'
q86dev='-device virtio-net-pci,netdev=unet -net user,id=unet -device virtio-scsi-pci'
