cat header2 src/csakey >> build/csakey
cat header2 src/cscmd >> build/cscmd
cat header2 src/cscon >> build/cscon
cat header2 src/csdkey >> build/csdkey
cat header2 src/csfwd >> build/csfwd
cat header2 src/cspkey >> build/cspkey
cat header2 src/csprofile >> build/csprofile
cat header2 src/cssend >> build/cssend
cat header2 src/cssendx >> build/cssendx
cat header2 src/csserver >> build/csserver
cat header2 src/csxdpy >> build/csxdpy
cat header2 src/csxkey >> build/csxkey
