cat header1 src/csakey >> build/csakey
cat header1 src/cscmd >> build/cscmd
cat header1 src/cscon >> build/cscon
cat header1 src/csdkey >> build/csdkey
cat header1 src/csfwd >> build/csfwd
cat header1 src/cspkey >> build/cspkey
cat header1 src/csprofile >> build/csprofile
cat header1 src/cssend >> build/cssend
cat header1 src/cssendx >> build/cssendx
cat header1 src/csserver >> build/csserver
cat header1 src/csxdpy >> build/csxdpy
cat header1 src/csxkey >> build/csxkey
