#!/bin/sh
#usage: utils/sacpref [identifier] (""|r|s)
#prefix.d preset syntax: [type]prefix.[identifier]
#type: "" / r / s
#identifier is a random string
pprefix=$(cat pprefix)
ptype=$2
pindex=$1
cat $pprefix/prefix.d/$ptype$(echo prefix).$pindex > $ptype$(echo prefix)
