#!/bin/sh
mount --bind /dev $ct_system/dev
mount --bind $ct_system/mem $ct_system/dev/shm
mount --bind $ct_system/rmem $ct_system/run/shm
mount --bind /proc proc
mount --bind /sys sys
chroot . /bin/su -c "sh $ct_initpath/initpty $ct_user" root
umount $ct_system/dev
umount $ct_system/dev/shm
umount $ct_system/run/shm
umount proc
umount sys
