#!/bin/sh
$xsh -YC -p "$port" $fwdruleset -i "$id" $user@"$hostname" -t "mkdir $svrex_remotestor"
$xcp -i "$id" -OCrp -P "$port" "$svrex_localstor/$svrex_exec" $user@$hostname:"$svrex_remotestor/$svrex_exec"
$xcp -i "$id" -OCrp -P "$port" "$dbfile" $user@$hostname:"$svrex_remotestor/$dbfile"
$xsh -YC -p "$port" $fwdruleset -i "$id" $user@"$hostname" -t "cd $svrex_remotestor && sh $svrex_exec $dbfile $entryname $svrex_args"
