#!/bin/sh
sh d2efbuild svformat svheader
sh csbuild svheader
rm d2ef.build0 d2ef.builder
rm csbuild.builder
lm=$(cat build/svtest | wc -l)
svt=$(cat build/svtest | sed '$d' | sed '$d')
echo "$svt" >> build/svtest
sed -i "$(($lm + 1)),\$s,=.*$,," build/svtest
sed -i "$(($lm + 1)),\$s,^.*$,echo &="\""\$&"\""," build/svtest
chmod -R 755 build/