#!/bin/sh
#csparse: a line parser for db-sabre
vname=$1
vsrcproc=$2
vsrcarg=$3
preproc=$4
filter=$5
postproc=$6
pos=$7
echo "$vname="\$\("$vsrcproc $vsrcarg | $preproc | grep $filter | $postproc | cut -d' ' -f$pos"\)
