#!/bin/sh
echo '' >> /home/sidearmconnect/.ssh/authorized_keys
cat /home/sidearmconnect/sacsshckey/key"$1" >> /home/sidearmconnect/.ssh/authorized_keys
echo '' >> /home/sidearmconnect/.ssh/authorized_keys
chown -R sidearmconnect /home/sidearmconnect/.ssh
chown -R sidearmconnect /home/sidearmconnect/.ssh/authorized_keys
chmod 0700 /home/sidearmconnect/.ssh
chmod 0600 /home/sidearmconnect/.ssh/authorized_keys
