#!/bin/sh
echo export https_proxy=socks5h://localhost:$2 >> .$(cat /etc/passwd | grep ^$1: | grep -o /.\*sh$ | sed s,^.\*bin/,,)rc
echo export http_proxy=socks5h://localhost:$2 >> .$(cat /etc/passwd | grep ^$1: | grep -o /.\*sh$ | sed s,^.\*bin/,,)rc
