#!/bin/sh
remote="$1"
port="$2"
fsource="$3"
fdest="$4"
prefix=$(cat prefix)
ruser=$5
rprefix=$(cat rprefix)
scp -i $prefix/sacsshhkey/key -O -P "$port" "$fsource" $ruser@$remote":$rprefix/sidearmconnect/rcvdest/"$fdest"
