#!/bin/sh
host=$1
port=$2
line=$3
prefix=$(cat prefix)
rprefix=$(cat rprefix)
ruser=$4
xauth list | grep -n '.\?' | grep '^'$line':' | sed 's,^[0-9]*:,,' > $prefix/sidearmconnect/sacfwdkey/key
scp -i $prefix/sidearmconnect/sacfwdkey/key -O -P "$port" "$fsource" $ruser@$remote:$rprefix/sidearmconnect/rcvdest/"$fdest"
